---
title: "Trabajo final"
editor: source
---

## Fecha de entrega

Al finalizar el curso, el estudiante deberá entregar un trabajo donde ponga en práctica lo aprendido. Este trabajo podrá ser entregado hasta la **media noche del día 30 de Abril** al correo electrónico del instructor.

## Opciones del trabajo

Este podrá ser:

1.    **Un reporte estadístico de alguna base de datos**: Ya sea en formato html, docx o pdf. El mismo deberá contener las siguientes secciones:

       
-   Resumen: Párrafo describiendo el problema a resolver (hipótesis de investigación), descripción de los métodos estadísticos usados, y mención de los resultados más importantes.

-   Introducción: Párrafo describiendo el estado actual de la pregunta de investigación (breve investigación bibliográfica) y que es lo nuevo que brinda el reporte con respecto a lo que ya se haya hecho antes.

-   Métodos: Descripción de la base de datos, técnicas estadísticas usadas para analizar los datos y cualquier otro aspecto que merezca ser mencionado (limpieza de datos, supuestos usados, etc).

-   Resultados: Gráficos, tablas, etc.

-   Conclusiones: Se respondió o no la pregunta de investigación, qué hemos aprendido que antes no se había descrito. Si los resultados son "negativos", no tener recelo en presentarlos. Idealmente, toda investigación debe ser reportada independientemente de si los resultados confirman o no la pregunta de investigación.

-   Bibliografía: cualquier formato es aceptado, libre a escoger por cada estudiante.

2.    **Presentación**: Ya sea en formato html, pptx o pdf conteniendo las mismas secciones que en 1 a excepción de la bibliografía (en caso de incluir citas en las diapositivas, las citas deben ser hechas como pies de diapositiva).

3.    **Portafolio/página web**: Para esta opción, el estudiante deberá crear una página web o portafolio a través de Github. La temática del portafolio es libre.

## Instrucciones para la presentación del trabajo

-   Independientemente de la opción que escoja el estudiante, **se deberá presentar el código fuente que generó el documento**.

-   En caso de no crear un repositorio de Github para las opciones 1 y 2, se deberá entregar en un archivo .zip el proyecto de R que contiene el trabajo y el documento renderizado.

-   En caso de haber creado un repositorio de Github para las opciones 1 y 2, se deberá entregar únicamente el documento renderizado acompañado del link del repositorio.

-   Para la opción 3, solo se puede presentar usando un repositorio de Github. El estudiante deberá enviar las direcciones electrónicas del repositorio y la página web/portafolio.

## Sobre la evaluación del trabajo

-   Para la aprobación del curso, el requisito mínimo es la presentación del trabajo final usando cualquiera de las opciones anteriormente mencionadas.

-   El intructor proveerá comentarios y consejos de como mejorar la presentación de resultados. Además, corregirá errores de interpretación o redacción de conclusiones estadísticas.

-   **La idea es que el estudiante aprenda a desarrollar un pensamiento estadístico apropiado en lugar de proveer soluciones puntuales como lo serían la resolución de problemas con una única respuesta**. En otras palabras, se busca motivar la interpretación crítica de resultados de problemas abiertos.

## Ayuda durante la realización del trabajo

-   El estudiante puede sentirse libre de contactar al instructor al correo electrónico **mmorenozambrano\@protonmail.com** o a través del grupo de **WhatsApp**.